#!/bin/bash
#don't try to run this script without makefile
echo 'generating templates/version.html...'

list=($(LC_ALL=en_US.UTF-8 ls -l --time-style="+%Y %b %d" bin/facebooc))
echo '<!--This file is auto-generated by "scripts/auto-update-html.sh" -->' >templates/version.html
echo "facebooc &copy; ${list[5]} <br>" >>templates/version.html
echo "Compile version: ${list[6]} ${list[7]}, ${list[5]}" >>templates/version.html

echo 'finish generating templates/version.html'
