#!/bin/bash
#don't try to run this script without makefile
echo 'generating templates/footer.html...'
list=(`LC_ALL=en_US.UTF-8 ls -l --time-style="+%Y %b %d" bin/facebooc`)
echo '<!--This class is auto-generated by "scripts/auto-gen-footer.sh" -->' > templates/footer.html
echo '<div class="footer">' >> templates/footer.html
echo -e "\tfacebooc &copy; ${list[5]} <br>" >> templates/footer.html
echo -e "\tCompile version: ${list[6]} ${list[7]}, ${list[5]}" >> templates/footer.html
echo '</div>' >> templates/footer.html

echo 'finish generating templates/footer.html'